apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
spec:
  kafkaClusters:
    - name: streams-kafka-3-cluster
      namespace: ${NAMESPACE}
      listener: plain
  hostname: kafka-console.${CLUSTER_DOMAIN}
  security:
    oidc:
      authServerUrl: ${AUTHSERVER}
      clientId: "streamshub-console"
      clientSecret:
          valueFrom:
            secretKeyRef:
              name: console-dex-secrets
              key: CONSOLE_SECURITY_OIDC_CLIENT_SECRET
