# This files configure the client properties for connecting to Kafka cluster.
security.protocol=SSL

# Truststore contains the Kafka cluster certificate
ssl.truststore.location=test-kafka-cluster-ca.p12
#ssl.truststore.location=custom-certificate.p12
ssl.truststore.password=passwd
ssl.truststore.type=PKCS12

# Keystroe contains the KafkaUser certificate
ssl.keystore.location=test-kakfa-user.p12
ssl.keystore.password=passwd
ssl.keystore.type=PKCS12

# Enable mTLS 
ssl.client.auth=required
ssl.endpoint.identification.algorithm=